---
title: 月云生
description: 月下飞天镜，云生结海楼。
locale: zh
email: "270453244qq.com"
url: "https://"
social:
  github: "yueyunsheng"
  twitter: ""
  codepen: ""

# Theme Settings
logo: /img/logo.svg
rss: "/feed.xml"
theme: 'jekyll-theme-persephone'
theme_setting:
  blog_page: "index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    - "archive.md"
  lang:
    category_all: "全部"
    blog_title: "博客"
    comment:
      user: "昵称"
      email: "邮箱"
      url: "链接"
      message: "说点什么吧..."
      reply: "回复"
comment:
  enabled: false
  provider: "static"
  static:
    postUrl: "https://jekyll-comment-server.herokuapp.com/post-comment"
    # postUrl: "https://g4vdkkahpjie.leanapp.cn/post-comment"
smiley:
  enabled: true
head_code: |
  <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?3176e6e675ed7773f831e38c7a57880f";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>

# Jekyll Settings
markdown: kramdown
permalink: /blog/:title:output_ext
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      keywords:
      description:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - scripts/
deploy:
  endpoint: "oss-cn-hongkong.aliyuncs.com"
  bucket_name: "erlim"
  expired_in: 1
  paths:
    - blog
    - feed.xml
    - sitemap.xml